module BNFC.SkelBugpan where

-- Haskell module generated by the BNF converter

import BNFC.AbsBugpan
import BNFC.ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transBIdent :: BIdent -> Result
transBIdent x = case x of
  BIdent str  -> failure x


transProgram :: Program -> Result
transProgram x = case x of
  Prog bident declares  -> failure x


transDeclare :: Declare -> Result
transDeclare x = case x of
  DLet pat args exp  -> failure x
  DImport bident  -> failure x
  DImportSubst bident impsubstlines  -> failure x
  DType bident type'  -> failure x
  DSinkConn exp1 bident2 exp3  -> failure x
  DReadSrc bident1 bident2 exp3  -> failure x
  DStage bident n  -> failure x
  DStageNeg bident n  -> failure x
  DEvery pat exp declares  -> failure x
  DDist pat exp  -> failure x
  DPragma bident exp  -> failure x


transExp :: Exp -> Result
transExp x = case x of
  Add exp1 exp2  -> failure x
  Sub exp1 exp2  -> failure x
  Mul exp1 exp2  -> failure x
  Div exp1 exp2  -> failure x
  EIn exp1 exp2  -> failure x
  Negate exp  -> failure x
  Natexp exp  -> failure x
  Natlog exp  -> failure x
  Realpart exp  -> failure x
  Imagpart exp  -> failure x
  EConst const  -> failure x
  And exp1 exp2  -> failure x
  Or exp1 exp2  -> failure x
  Not exp  -> failure x
  ECmp exp1 cmpop2 exp3  -> failure x
  If exp1 exp2 exp3  -> failure x
  Lam pat exp  -> failure x
  App exp1 exp2  -> failure x
  Var bident  -> failure x
  Pair exp1 exp2  -> failure x
  Pair3 exp1 exp2 exp3  -> failure x
  Nil  -> failure x
  Cons exp1 exp2  -> failure x
  ListLit exps  -> failure x
  Sig exp  -> failure x
  SigLimited exp1 exp2  -> failure x
  SigVal exp  -> failure x
  SigAt exp1 exp2  -> failure x
  SigDelay exp1 exp2  -> failure x
  SigDeriv exp  -> failure x
  SigFby exp1 exp2  -> failure x
  Event exp  -> failure x
  ETest exp1 exp2  -> failure x
  EScan exp1 exp2  -> failure x
  Forget exp1 exp2  -> failure x
  Switch exp switchlines  -> failure x
  Box exp  -> failure x
  Translate exp1 exp2  -> failure x
  Colour exp1 exp2  -> failure x
  ELet declares exp  -> failure x
  ECase exp caselines  -> failure x


transSwitchLine :: SwitchLine -> Result
transSwitchLine x = case x of
  SwitchLine exp1 exp2  -> failure x


transCaseLine :: CaseLine -> Result
transCaseLine x = case x of
  CaseLine pat exp  -> failure x


transArg :: Arg -> Result
transArg x = case x of
  Arg pat  -> failure x


transImpSubstLine :: ImpSubstLine -> Result
transImpSubstLine x = case x of
  ImpSubstLine bident exp  -> failure x


transPat :: Pat -> Result
transPat x = case x of
  PVar bident  -> failure x
  PWild  -> failure x
  PLit const  -> failure x
  PPair pat1 pat2  -> failure x
  PNil  -> failure x
  PCons pat1 pat2  -> failure x
  PIn pat1 pat2  -> failure x
  PDeriv pat  -> failure x
  PRemember pat  -> failure x


transConst :: Const -> Result
transConst x = case x of
  CInt n  -> failure x
  CDbl d  -> failure x
  CUnit  -> failure x
  CTrue  -> failure x
  CFalse  -> failure x
  CString str  -> failure x


transCmpOp :: CmpOp -> Result
transCmpOp x = case x of
  Lt  -> failure x
  Gt  -> failure x
  Le  -> failure x
  Ge  -> failure x
  Eq  -> failure x
  Ne  -> failure x


transType :: Type -> Result
transType x = case x of
  TUnit  -> failure x
  TLam type'1 type'2  -> failure x
  TPair2 type'1 type'2  -> failure x
  TPair3 type'1 type'2 type'3  -> failure x
  TNum  -> failure x
  TReal  -> failure x
  TInt  -> failure x
  TBool  -> failure x
  TShape  -> failure x
  TSignal type'  -> failure x
  TEvent type'  -> failure x
  TDuration type'  -> failure x
  TList type'  -> failure x
  TyVar bident  -> failure x



